import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/home/Feed'

const style = {
  wrapper: `flex justify-center h-screen w-screen select-none bg-[#15202b] text-white`,
  content: `max-w-[1400px] w-2/3 flex justify-between`, 
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.wrapper}>
        <div className={style.content}>
          <Sidebar/>
          <Feed />
          <h2>Widgets</h2>
        </div>
      </div>
    </>
  )
}
